#!/usr/bin/env python3
"""Generates src/tokenizer/unicode_tables.inc: the code-point ranges for the
Unicode general categories L (letters) and N (numbers), which the GPT-2
pre-tokenizer pattern uses as \\p{L} and \\p{N}.

It also writes the N ranges of a second Unicode version for the Digits
pre-tokenizer: the reference implementation splits digits with Rust's
char::is_numeric, whose tables are a newer Unicode version than its regex
engine's. docs/tokenizer.md shows how both versions were determined.

Input is UnicodeData.txt from the Unicode Character Database, so each version
is explicit:

  curl -sS -o UnicodeData-16.txt https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt
  curl -sS -o UnicodeData-17.txt https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt
  python3 tools/gen_unicode_tables.py UnicodeData-16.txt 16.0.0 UnicodeData-17.txt 17.0.0 \
      > src/tokenizer/unicode_tables.inc
"""
import sys


def categories(path):
    """Yields (first, last, category) for every assigned code point range."""
    pending = None
    with open(path, encoding="utf-8") as f:
        for line in f:
            fields = line.rstrip("\n").split(";")
            cp, name, cat = int(fields[0], 16), fields[1], fields[2]
            if name.endswith(", First>"):
                pending = cp
                continue
            if name.endswith(", Last>"):
                yield pending, cp, cat
                pending = None
                continue
            yield cp, cp, cat


def ranges(path, major):
    out = []
    for first, last, cat in categories(path):
        if cat[0] != major:
            continue
        if out and out[-1][1] + 1 == first:
            out[-1] = (out[-1][0], last)
        else:
            out.append((first, last))
    return out


def emit(name, rs):
    print(f"constexpr CodeRange {name}[] = {{")
    for i in range(0, len(rs), 4):
        print("    " + " ".join(f"{{0x{a:X}, 0x{b:X}}}," for a, b in rs[i:i + 4]))
    print("};")


def main():
    if len(sys.argv) != 5:
        sys.exit("usage: gen_unicode_tables.py REGEX_UnicodeData.txt VERSION DIGITS_UnicodeData.txt VERSION")
    regex_path, regex_version, digits_path, digits_version = sys.argv[1:]
    print("// Generated by tools/gen_unicode_tables.py from UnicodeData.txt. Do not edit.")
    print(f"// Pattern classes \\p{{L}} and \\p{{N}}: Unicode {regex_version}. Digits pre-tokenizer: Unicode {digits_version}.")
    print(f'constexpr const char* kUnicodeVersion = "{regex_version}";')
    print(f'constexpr const char* kDigitsUnicodeVersion = "{digits_version}";')
    emit("kLetterRanges", ranges(regex_path, "L"))
    emit("kNumberRanges", ranges(regex_path, "N"))
    emit("kNumericRanges", ranges(digits_path, "N"))


if __name__ == "__main__":
    main()
